// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrZqjhzr2xNUfF26Ohefi3-u8rZMUw1lQ',
    appId: '1:104094628325:web:4072db250ffda0a295170c',
    messagingSenderId: '104094628325',
    projectId: 'push-d7f74',
    authDomain: 'push-d7f74.firebaseapp.com',
    storageBucket: 'push-d7f74.firebasestorage.app',
    measurementId: 'G-SF3LYPG4FW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9pYH4pc0cgaWc_ol0iXlD4pQTaNDdnOs',
    appId: '1:104094628325:android:098c12295a9512bc95170c',
    messagingSenderId: '104094628325',
    projectId: 'push-d7f74',
    storageBucket: 'push-d7f74.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrZqjhzr2xNUfF26Ohefi3-u8rZMUw1lQ',
    appId: '1:104094628325:web:eb605070802a138195170c',
    messagingSenderId: '104094628325',
    projectId: 'push-d7f74',
    authDomain: 'push-d7f74.firebaseapp.com',
    storageBucket: 'push-d7f74.firebasestorage.app',
    measurementId: 'G-Z8K20J15DV',
  );
}
